<?php

return [
    //header content starts here
    'home' => 'Home',
    'action_rpgs' => 'Action RPGs',
    'esports' => 'Esports',
    'sandbox' => 'Sandbox',
    'strategy' => 'Strategy',
    'contact_us' => 'Contact Us',
    'games' => 'GAMES',
    'live_streams' => 'Live Streams',
    'stream_details' => 'Stream Details',
    'match_results' => 'Match Results',
    'tournaments' => 'Tournaments',
    'tournament_details' => 'Tournament Details',
    'about_us' => 'About Us',
    'database' => 'Database',
    'faqs' => 'FAQs',
    'contact_us' => 'Contact Us',
    'shopping_cart' => 'Shopping Cart',
    'subtotal' => 'Subtotal',
    'view_cart' => 'View Cart',
    'checkout' => 'Checkout',
    // Points Top Up – Section
    'points_topup_title' => 'Points Top Up',
    'points_topup_tagline' => 'Recharge. Multiply. Enjoy More Value.',
    'points_topup_intro_1' => 'Upgrade your experience instantly with our enhanced point recharge system. Every time you top up, you unlock bonus points — automatically. No promo codes, no conditions, just pure value on every recharge.',
    'points_topup_intro_2' => 'Whether you\'re making a small top-up or going big, our bonus tiers ensure you always get more than what you pay for.',

    // Bonus Tier
    'bonus_tier_title' => 'Bonus Tier Structure',
    'bonus_table_range' => 'Top-Up Range',
    'bonus_table_multiplier' => 'Bonus Multiplier',
    'bonus_table_benefit' => 'What You Get',

    'bonus_standard' => 'Standard points',
    'bonus_50_extra' => '50% extra points',
    'bonus_100_extra' => '100% extra points',
    'bonus_400_extra' => '400% extra points',
    '3201_and_above' => '$3,201 and above',
    '500,001_and_above' => '¥500,001 and above',

    'bonus_note' => 'Your bonuses apply instantly. No codes, no waiting — just pure value on every recharge.',
    'disclaimer' => 'Disclaimer: All purchased points can only be redeemed on this website.',
    'purchase_services' => 'Purchase',
    'available_credits' => 'Available Points',
    'credits' => 'Points',
  'points' => 'Points',
    'bonus_points' => 'Bonus Points',
    'total_points' => 'Total Points',
    // How it works
    'how_it_works_title' => 'How It Works',
    'how_step_1' => 'Choose your desired recharge amount',
    'how_step_2' => 'Bonus points are automatically calculated',
    'how_step_3' => 'Complete payment',
    'how_step_4' => 'Your boosted points appear instantly in your account',

    // CTA
    'start_recharge_title' => 'Start Your Recharge Now',
    'start_recharge_text' => 'Get more value with every top-up — the more you recharge, the more you earn.',
    'start_recharge_button' => 'Enter The Amount & Recharge Now',
     // Form
    'label_amount' => 'Amount',
    'redeem_cart'=>'Redeem Cart',
    'label_points' => 'Points',
    'placeholder_amount' => 'Enter amount in :currency',
    'placeholder_points' => 'Number Of Points',
   'add_cart' => 'Add To Cart',

    //footer content starts here
    'subscribe_our_newsletter' => 'Subscribe Our Newsletter',
    'success_message' => ' Welcome Aboard! You’ve successfully subscribed.',
    'utility_pages' => 'Utility Pages',
    'delivery_policy' => 'Delivery Policy',
    'privacy_policy' => 'Privacy Policy',
    'refund_policy' => 'Refund Policy',
    'terms_conditions' => 'Terms & Conditions',
    'genres' => 'Genres',
    'oops' => 'Oops....',
'this_link_does_not' => 'This link does not seem to exist.',
'please_go' => 'Please go to the homepage again.',
'go_to_homepage' => 'Go To Homepage',
'currency_changed' =>'Currency Changed to ',
'high_traffic' => 'We’re currently experiencing high traffic, which may delay the delivery of your invoice by email. You can download your invoice here in the meantime.',


    //home page content starts here
    'gaming_zone' => 'Gaming Zone',
    'game_on' => 'Game On - Thrilling',
    'challenges' => 'Challenges',
    'boost_your_rank1' => 'Boost your rank, master your skills, and achieve your gaming goals',
    'boost_your_rank2' => 'faster with our professional game boosting services. Safe, secure,',
    'boost_your_rank3' => 'and hassle-free progress—every step of the way.',
    'join_now' => 'Join Now',
    'read_more' => 'Read More',
    'fast_secure' => 'Fast & Secure Boosting',
    'fast_secure_desc' => 'Experience seamless boosting with guaranteed results. Our team ensures your rank climbs quickly while maintaining top-level security.',
    'expert_boosters' => 'Expert Boosters',
    'expert_boosters_desc' => 'Get support from highly skilled professionals who know every tactic, strategy, and shortcut to maximize your progress.',
    'guaranteed_progress' => 'Guaranteed Progress',
    'guaranteed_progress_desc' => 'Whether it’s rank climbing, K/D improvement, or unlocking rare items, we guarantee visible improvement in minimal time.',
    'safe_confidential' => 'Safe & Confidential',
    'safe_confidential_desc' => 'Your privacy is our priority. We use advanced protection measures to keep your account safe throughout the process.',
    'game_streams' => 'Game Streams',
    'coming' => 'Coming',
    'soon' => 'Soon',
    'cod_tournament' => 'COD Tournament',
    'cod_tournament_desc' => 'Join the ultimate gaming showdown and boost your skills to the next level! Compete with top players, earn exclusive rewards, and climb the leaderboards like a pro.',
    'check_detail' => 'Check Detail',
    'follow_on' => 'Follow on',
    'best_sellers' => 'Best Sellers',
    'about_gameover' => 'About Warp Strike',
    'level_up_with_expert_coaching' => 'Level Up with Expert Coaching',
    'at_gameover' => 'At Warp Strike, we empower gamers to unlock their true potential through personalized coaching services. Our team of professional players and skilled mentors provide one-on-one sessions, tailored strategies, and in-depth analysis to help you refine your skills, master game mechanics, and gain a competitive edge.',
    'whether_youre_aiming' => 'Whether you\'re aiming to climb ranks, enhance your K/D ratio, or improve teamwork and decision-making, our coaching programs are designed to suit every playstyle and skill level. We combine expert insights with proven training methods to ensure steady progress while keeping your gaming experience enjoyable and rewarding.',
    
    //About Us Page Content starts here
    'company' => 'Company',
    'who_we_are' => 'who we are',
     'built_for_gamers' => 'Built for Gamers Who Want More',
      'next_gen_platform' => 'We are a next-generation gaming support platform created for players who want to progress smarter, play better, and experience more from their games without unnecessary limitations.',
      'team_description' => 'Our team brings together competitive players, analysts, and gaming enthusiasts who understand both the challenges and the excitement of modern online gaming. Instead of treating gaming services as simple transactions, we focus on delivering meaningful improvements to your overall experience — whether that means faster progression, unlocking opportunities, or gaining a competitive edge.',
    'immerse_yourself' => 'Immerse Yourself in the Gaming Experience',
    'immerse_yourself_desc' => 'Step into a world where every match matters. Our expert game boosting services help you achieve your desired ranks, unlock rare rewards, and experience the thrill of gaming without the grind.',
    'immerse_yourself_desc_2' => 'From rank climbing to K/D improvement, we ensure your gameplay becomes smoother, faster, and more rewarding—while you stay in control of your account and enjoy complete security.',
    'explore_our_services' => 'Explore Our Services',
    'beyond_boundaries' => 'Beyond Boundaries: Where Gaming Dreams Come True',
    'beyond_boundaries_desc' => 'Take your skills beyond limits with our premium coaching and boosting solutions. Whether you want to dominate leaderboards, complete challenging missions, or unlock elite achievements, we make it possible.',
    'beyond_boundaries_desc_2' => 'With our professional boosters and proven strategies, every goal becomes achievable—safe, efficient, and hassle-free. Start your journey toward gaming greatness today!',
    
    //cart page content starts here
    'products_details' => 'Products Details',
    'no_cart_available' => 'Your cart is empty',
    'continue_shopping' => 'Continue Shopping',
    'order_summary' => 'Order Summary',
    'items' => 'Items',
    'quantity' => 'Quantity',
    'price' => 'Price',
    'total' => 'Total',
    'remove' => 'Remove',
    'checkout' => 'Checkout',
    'remove_product'=>'Product removed successfully',
    

    //checkout page content starts here
    'additional_information' => 'Additional information',
    'notes' => 'Notes',
    'notes_about_order' => 'Notes about order',
    'card_holder_name' => 'Card Holder Name',
    'card_number' => 'Card Number',
    'expiry_month' => 'Expiry Month',
    'cvv' => 'CVV',
    'agree_terms_text' => 'I have read and agree to the',

    //contact page content starts here
    'lets_get_in_touch' => "Let's Get in Touch",
    'contact_form' => 'Contact Form',
    'send_message' => 'Send Message',

    //database page content starts here
    'there_are_no_products' => 'There are no products.',

    //forget password page content starts here
    'forget_password' => 'Forget Password',
    'submit' => 'Submit',
    'if_you_dont_have_account' => 'If you don’t have account?',

    //login page content starts here
    'Keep_me_logged_in' => 'Keep me logged in',

    //product details page content starts here
    'review' => 'Review',
    'optional_training_add_on' => 'Optional Training Add-on',
    'please_choose_number_of_hours' => 'Please choose number of hours of training.',
    'training_subtitle' => 'Watch, Learn, and Improve While We Boost Your Account',
    'training_intro_1' => 'Take your gaming skills to the next level with our exclusive live coaching experience, offered as an optional add-on to your boosting service.',
    'training_intro_2' => 'By selecting the number of hours using the slider above, you\'re not just getting a regular boost — you\'re unlocking a personalized training session where you can watch our professional player boost your account live, while they guide you through every decision, strategy, and mechanic in real time.',
    'training_intro_3' => 'This service is perfect for players who not only want their account to climb ranks but also want to understand how to improve their gameplay along the way.',
    'training_included_title' => 'What’s Included in the Training Add-On?',
    'training_live_spectating' => 'Live Spectating Access',
    'training_live_spectating_desc' => 'You’ll be able to watch your assigned booster play live via screen share (platform options available after purchase). This lets you observe their gameplay as it happens — no replays, no edits — just pure, professional-level execution.',
    'training_real_time_instruction' => 'Real-Time Instruction & Commentary',
    'training_real_time_instruction_desc' => 'As the booster plays, they’ll explain their strategies, call out key decisions, and share their thought process. You’ll learn exactly why they make certain plays, rotate the way they do, or use abilities/items at specific moments.',
    'training_interactive_learning' => 'Interactive Learning Experience',
    'training_interactive_learning_desc' => 'Got questions? Want clarification? You can interact live during the session, either through voice chat or text, depending on your preference. This turns your session into an immersive coaching environment.',
    'training_skill_development' => 'Skill Development Focus',
    'training_skill_development_desc' => 'Whether you\'re trying to master positioning, decision-making, game sense, aiming, movement, or meta strategies — this experience is tailored to teach you what truly works at higher ranks.',
    'training_pricing_title' => 'How Pricing Works',
    'training_pricing_desc' => 'This training add-on is priced per hour, as shown above with the slider. It is charged separately from the core boosting package, and you can choose the number of hours based on how long you\'d like to observe and train.',
    'training_notes_title' => 'Important Notes',
    'training_note_1' => 'The training session is conducted while your boost is being completed, so you’ll benefit from seeing your account grow in real time.',
    'training_note_2' => 'All sessions are private and secure. No third parties involved — just you and your assigned booster.',
    'training_note_3' => 'This service is completely optional. If you only want the boost without live training, you can skip the slider and proceed as usual.',
    'training_final_title' => 'Ready to level up your skills while leveling up your account?',
    'training_final_desc' => 'Use the slider above to select the number of training hours and unlock elite-level insights from pro players.',
    'all_packs' => 'All Packs',
'hours' => 'hours optional training',


    //register page content starts here
    'create_an_account' => 'Create an Account',
    'sign_up_with_your_email_address' => 'Sign up with your email address',
    'create_account' => 'Create Account',
    'already_have_an_account' => 'Already have an account?',
    'log_in' => 'Log In',
'fill_it' => 'Please fill this required field',
    'fill_captcha' => 'Enter the code',
    'captcha_error' => 'Invalid code from the image',
    //user dashboard page content starts here
    'order_history' => 'Order History',
    'change_password' => 'Change Password',
    'logout' => 'Logout',
    'serial_number' => 'S.No.',
    'continue' => 'Continue',
    'back' => 'Back',
    'current_password' => 'Current Password',
    'new_password' => 'New Password',
    'confirm_new_password' => 'Confirm New Password',
    
    //end 








   //About-us Content
     'our_story_text' => 'Our Story',
     'our_story_para' => 'Founded over a decade ago, we started as a trio of tech wizards and storytellers obsessed with solving real business problems. Today, our full-service digital alchemy lab has empowered 99,000+ brands across 20+ industries – from scrappy startups to Fortune 500 partners like Google, Meta, and Shopify.',
     'why_we_diff' => 'Why We’re Different',
     'about_heading_2' => 'The Human Touch in Digital Spaces',
     'about_para_2' => '"We don’t believe in clients – we believe in friends." Every project begins with empathy interviews to understand your audience’s deepest desires. Our 96% satisfaction rate comes from treating your KPIs like our own.',
     'about_heading_3' => 'End-to-End Digital Magic',
     'about_sub-heading' => 'From brand taglines to multi-channel campaigns, we’re your:',
     'team_roles' => [
        'storytellers' => 'Storytellers (Branding/Content)',
        'scientists' => ' Scientists (ROAS-Driven Ads)',
        'engineers' => 'Engineers (Web/E-commerce)',
        'community_builders' => 'Community Builders (Social Media)',
    ],
    'integrity_title' => '🔰 Integrity',
    'integrity_desc' => 'We restore devices – and trust.',

    'adaptability_title' => '🦎 Adaptability',
    'adaptability_desc' => 'Pivoting faster than tech trends.',

    'magic_title' => '✨ Magic',
    'magic_desc' => 'The ‘wow’ in every wireframe.',
    'years_title' => '10+ Years',
    'years_desc' => 'Of transforming "what ifs" into "what’s next"',

    'brands_title' => '500+',
    'brands_desc' => 'Brands launched or reinvented',

    'roas_title' => '32X',
    'roas_desc' => 'Highest ROAS delivered for a client',

    'partnerships_title' => '20+',
    'partnerships_desc' => 'Global tech partnerships',
     'previous' => '&laquo; Previous',
    'next' => 'Next &raquo;',
    'meet_team_title' => 'Meet the Wizards Behind the Curtain',

    'team' => [
        'alex' => [
            'name' => 'Alex Chen',
            'role' => 'Chief Technomancer',
            'description' => 'Breaks code and stereotypes since 2012',
        ],
        'priya' => [
            'name' => 'Priya Kapoor',
            'role' => 'Brand Spellcaster',
            'description' => 'Turns coffee into taglines',
        ],
        'jamal' => [
            'name' => 'Jamal Wright',
            'role' => 'Data Alchemist',
            'description' => 'Makes spreadsheets tell fairy tales',
        ],
    ],
    // Header Content starts here
    'home'=> 'Home',
    'about' =>'About Us',
    'contact' => 'Contact Us',
    'our_services' =>'Our Courses',
    'view_cart' => 'View Cart',
    'checkout' => 'Checkout',
    'account' => 'Account',
    'instructors' => 'Instructors',
    'login' => 'Login',
    'logout' => 'Logout',
    'register' => 'Register',
    'call_anytime' =>'Email Us',
    'welcome_code' => 'Empower Your Future with Knowledge - Choose your course and Enroll Now!!!',
    'at_checkout' => 'at checkout to enjoy a',
    'discount_value' => '10% discount',
    'on_any_course' => 'on any course!',
//Home page Content starts here
'best' => 'Best',
'home_subtext' => "Whether you're upskilling or exploring new passions, there's something here for everyone.",
'view_all_courses' => 'View all Courses',
    'discover_your_journey' => 'Discover your journey',
    'discover' => 'Discover',
    'courses_from_top_instructors' => 'Courses from top Instructors Around the World',
    'top_rated_instructors' => 'Top Rated Instructors',
    'more_than' => 'More than',
    'more_than_students' => 'students enrolled around the world',
    'explore' => 'Explore',
    'our_top' => 'Our Top',
    '25000_and_above'=>'25000 and above',
    'our_core' => 'Our Core',
    'services' => 'Services',
    'worlds_best' => "World's Best",
    'courses' => 'Courses',
    'view_all' => 'View All',
    'connect_with_industry_leaders' => 'Connect with industry leaders in virtual forums',
    'comprehensive_exam_support' => 'Comprehensive support for various exam',
    'flexible_modules' => 'Choose from evening or weekend modules',
    'skills_and_careers_message' => "Building skills and accelerating careers shouldn’t be an afterthought. In today’s competitive world, learners are looking for meaningful, flexible, and result-driven education—and that’s exactly what we deliver.",
    'upgrade_future_message' => "With expert-designed content and learner-first tools, we’re helping thousands upgrade their future.",
    'interactive_learning' => 'Interactive Learning Experience',
    'simple_enrollment' => 'Simple & Seamless Enrollment',
    'expert_instructors' => 'Expert Instructors from Industry',
    'more_about_us' => 'More about us',
    'free_shipping' => 'Free Shipping',
    'free_shipping_info' => 'Free shipping on all US orders or above $200',
    'support_24_7' => '24x7 Support',
    'why_students' => 'Why Students',
    'choose_us' => 'Choose Us',
    'gain_knowledge' => 'for Gain Their Knowledge',
    'discover_your_gain' => 'Discover your gain',
    'learn_at_your_own_pace' => 'Learn at your own pace, anytime, anywhere — with content tailored for real-world success.',
    'browse_courses' => 'Browse courses',
    'behavioral_finance' => 'Behavioral Finance & Decision Making',
    'corporate_finance' => 'Corporate Finance & Valuation',
    'personal_financial_mastery' => 'Personal Financial Mastery',
    'advanced_portfolio_management' => 'Advanced Portfolio Management',
    'foundations_investing_professionals' => 'Foundations of Investing for Professionals',
'section2_heading' => 'Work together for your business success',
'welcome_description' =>'At EC Shop Limited, we partner with ambitious businesses to turn digital challenges into growth opportunities. Whether you need a stunning website, data-driven marketing campaigns, or a cohesive social media strategy, our Hong Kong-based team delivers results that matter.',
'welcome_point1' => 'Strategic Expertise – Local market knowledge paired with global digital trends.',
'welcome_point2' => 'Tailored Solutions – No cookie-cutter approaches—just strategies built for your goals.',
'welcome_point3' => 'Transparent Process – Clear communication, measurable outcomes, and continuous optimization.',
'welcome_heading2' => 'Free Consultation',
'welcome_suheading2' => 'Kickstart your digital journey with a no-obligation consultation. Let’s discuss your goals, analyze your current presence, and outline actionable steps to elevate your brand—all at no cost.',
'banner_heading' => 'Where Creative Strategy Meets Performance Science',
'banner_desc' => 'We transform marketing budgets into revenue generators, delivering campaigns that consistently achieve 32X returns (like we did for Matrix Partners and 200+ global clients).',
'benefit1' => 'ROI-Focused Campaigns ',
'benefit2' => 'Industry-Specific Strategies',
'benefit3' => 'Transparent Pricing',
'benefit4' => 'Agile Execution',
'benefit_desc_1' => 'Maximize your business potential with our campaigns designed to deliver measurable results and drive sustainable growth.',
'benefit_desc_2' => 'Tailored industry-specific strategies that cater to your unique needs, ensuring a competitive edge in your market.',
'benefit_desc_3' => 'Clear, upfront pricing with no hidden fees – so you can choose with confidence and see exactly what you’re getting.',
'benefit_desc_4' => 'Agile execution that adapts to your needs, ensuring fast, flexible, and efficient delivery of results.',
'discover_more' => 'Our Story',
//Section-3

'our_strength' => 'Our Strengths',
'section3_heading' =>'What are our core strengths',
'strength1' => 'Ui / Ux Creative design',
'strength1_text' => 'At EC Shop-Marketing, we don’t just design interfaces – we create engaging, intuitive, and user-centered experiences that captivate and convert. Our UI/UX expertise ensures that every interaction on your website or digital platform is smooth, meaningful, and visually appealing.
Why Our UI/UX Design Stands Out:',
'design_principles' => [
    'user_centric' => 'User-Centric Approach – We prioritize user behavior, accessibility, and seamless navigation to enhance engagement.',
    'stunning_designs' => 'Visually Stunning Designs – A perfect blend of aesthetics and functionality for a modern, professional look.',
    'performance' => 'Performance-Optimized Interfaces – Speed, responsiveness, and clarity that drive better user retention.',
    'compatibility' => ' Multi-Device Compatibility – Flawless experiences across desktop, mobile, and tablet screens.',
],

    'final_message' => 'With a deep understanding of industry trends and user expectations, we craft digital experiences that leave a lasting impact. Let’s build a design that speaks to your audience and drives real results!',
'strength2' => 'Visual graphic design',
'strength2_text' =>'At EC Shop Limited, we bring ideas to life with eye-catching visuals that captivate and communicate. Our expert graphic designers craft high-quality visuals that enhance your brand identity, engage your audience, and leave a lasting impression.',
'graphic_design' => [
        "custom_designs" => "Creative & Custom Designs - Unique, tailor-made graphics that align with your brand vision.",
        "visual_storytelling" => "High-Impact Visual Storytelling - Designs that don't just look good but tell your brand's story effectively.",
        "versatile_platforms" => "Versatile Across Platforms - Perfectly optimized for websites, social media, ads, and print.",
        "trend_aesthetics" => "Trend-Driven Aesthetics - Modern, stylish, and engaging designs that resonate with your audience.",
    ],
    'strength3' => 'Data Driven Strategies',
    'strength3_text' =>'At EC Shop Limited, we don’t rely on guesswork—we use powerful data insights to drive every decision. Our data-driven strategies help businesses optimize performance, improve targeting, and achieve measurable growth.',
    'data_driven_strategy' => [
    "insightful_analytics" => "Insightful Analytics - We analyze user behavior, market trends, and performance metrics to refine strategies.",
    "precision_targeting" => "Precision Targeting - Reach the right audience at the right time with hyper-focused marketing.",
    "continuous_optimization" => "Continuous Optimization - Real-time tracking and adjustments for better conversions and ROI.",
    "fact_based_decision" => "Fact-Based Decision Making - No assumptions, just smart strategies backed by data.",
],
'company_benefits' => 'Company Benefits',
    'customer_journey' => 'We care about every stage in a customer journey',
    'providing_innovative' => 'Providing innovative Website solutions for future.',
    'cutting_edge_solutions' => 'We provide cutting-edge website solutions that are designed to adapt to the evolving digital landscape, ensuring seamless user experiences, enhanced functionality, and future-proof scalability for your business.',
    'our_mission' => 'Our Mission',
    'our_vision' => 'Our Vision',
    'our_story' => 'Our Story',
    'mission_statement' => 'To empower businesses with innovative, intuitive, and sustainable web solutions that drive growth, enhance user engagement, and shape the future of the digital world.',
   'custom_website_design' => 'Custom Website Design',
    'responsive_design' => 'Responsive Design',
    'seo_performance_optimization' => 'SEO & Performance Optimization',
    'ongoing_support_maintenance' => 'Ongoing Support & Maintenance',
    'vision_statement' => 'To deliver high-quality, tailored website solutions that exceed client expectations, foster meaningful connections, and continuously evolve to meet the dynamic needs of the digital age.',
    'company_history' => 'Founded over a decade ago, we started as a trio of tech wizards and storytellers obsessed with solving real business problems. Today, our full-service digital alchemy lab has empowered 99,000+ brands across 20+ industries – from scrappy startups to Fortune 500 partners like Google, Meta, and Shopify.',

//Homepage other Sections content 
'ecshop_marketing_intro' => 'Ecshop Marketing is ready to protect your businesses',
'ecshop_start_project' => "Let’s Start Your Project with Ecshop Marketing",
'projects_completed' => 'Projects Completed',
'satisfied_clients' => 'Satisfied Clients',
'expert_teams' => 'Expert Teams',
'passion_and_skill' => 'The passion, trying & skill can make a top-performing company',
'lets_get_started' => "Let’s get started",

//Product_Lists Page content starts here 
'shop' => 'Our Courses',
    'price' => 'Price',
    'filter' => 'Filter',
    'categories' => 'Categories',
    'business' => 'Business',
    'introductions' => 'Introductions',
    'one_page_template' => 'One Page Template',
    'parallax_effects' => 'Parallax Effects',
    'new_technologies' => 'New Technologies',
    'video_backgrounds' => 'Video Backgrounds',
    'showing_results' => 'Showing 1–9 of 12 results',
    'sort_by_popular' => 'Sort by Popular',
    'sort_by_price' => 'Sort by Price',
    'sort_by_ratings' => 'Sort by Ratings',

//Product Details Page content starts here
    'customer_reviews' => 'Customer Reviews',
    'quantity' => 'Quantity',
    'products' => 'Products',
    'add_to_wishlist' => 'Add to Wishlist',
    'add_to_cart' => 'Add to Cart',
    'description' => 'Description',
    'add_a_review' => 'Add a Review',
    'submit_review' => 'Submit Review',
    'you_need_to' => 'You need to',
    'or' => 'OR',
    'reviews' => 'Reviews',
    'rate_this_product' => 'Rate this Product?',
    'overall' => '(Overall)',
    'category' => 'Category :',
    'based_on' => 'Based on',
    'comments' => 'Comments',


    // Contact Us Page Contents Starts here 
    'get_in_touch' => 'Get in touch',
    'query_note' => 'Note: Queries/complaints will be attended within 3 business days.',
    'write_message' => 'Write us a message ',
    'login_first' => '[You need to login first]',
    'your_name' => 'Your Name',
    'enter_name' => 'Enter your name',
    'your_subject' => 'Your Subjects',
    'enter_subject' => 'Enter Subject',
    'your_email' => 'Your Email',
    'enter_email' => 'Enter email address',
    'your_phone' => 'Your Phone',
    'enter_phone' => 'Enter your phone',
    'your_message' => 'Your message',
    'mobile' => 'Mobile',
    'location' => 'Location',
    'enter_message' => 'Enter Message',
    'send_message' => 'Send Message',

//Footer Page contents start here 
'company_info' => 'Company Info',
'company_name' => 'Business Name',
'company_phone' => '+6588565865',
'company_email' => 'info@eliteliftgaming.com',
'company_address' => 'Unit 308, 3/F, Chevalier House 45-51 Chatham Road South, Tsim Sha Tsui, Hong Kong',
     'lets_work_together' => "Let's work together just drop me a line -",
     'links' => 'Links',
     'category' => 'Category',
     'about1' => 'About',
     'terms_policy' => 'Terms & Conditions',
     'privacy_policy' => 'Privacy Policy',
     'delivery_policy' => 'Delivery Policy', 
     'refund_policy' => 'Refund Policy',
     'browse_categories' => 'Browse Categories',
     'quick_links' => 'Quick Links',
     'have_question' => 'Have a question? Connect with us 24/7',
     'copyright_notice' => 'Simply All Beauty',
     'all_right_reserved' => 'All Rights Reserved.',
     'site_description' => 'Simply All Beauty is the biggest wellness store. Get your daily needs from our store.',


// Register Page Content starts here
'register_subtext' => 'Please register in order to checkout more quickly',
'login_here_text' => 'Log in here',
'login_subtext' => 'Please login in order to checkout more quickly',
"already_account" => 'Already have an account? ',
'name' => "Name",
'email' =>'Email',
'password' =>'Password',
'confirm_password' => 'Confirm Password',
'im_new_here' => __('I\'m new here'),
    'signup_promotion' => __('Sign up for early sale access plus tailored new arrivals, trends, and promotions.'),
//Cart page contents starts here 

'cart' => 'Cart',
    'item' => 'Item',
    'total' => 'Total',
    'remove' => 'Remove',
    'no_cart_available' => 'Your cart is empty',
    'continue_shopping' => 'Continue Shopping',
    'apply_coupon' => 'Apply Coupon',
    'update' => 'Update',
    'checkout' => 'Checkout',
    'shopping_cart' => 'Shopping Cart',
    'cart_total' => 'Cart Totals',


    //Checkout Page contents Starts here 
    'terms_agreement' => 'I have read and agree to the',
    'product' => 'Product',
    'returning_customer' => 'Returning Customer?',
    'click_here_to_login' => 'Click here to Login',
    'billing_details' => 'Billing Details',
    'town_city' => 'Town / City',
    'state' => 'State',
    'zip_code' => 'Zip code',
    'phone' => 'Phone',
    'your_order' => 'Your Order',
    'select_country' => 'Select Country',
    'subtotal' => 'Subtotal',
    'card_details' => 'Card Details',
    'credit_card' => 'Credit Card',
    'card_number' => 'Card Number',
    'card_expiry' => 'Card Expiry',
    'card_cvc' => 'Card CVC',
    'country' => 'Country',
    'card_holder_name' => 'Card Holder Name',
    'place_your_order' => 'Place your order',
    'place_order' => 'Place order',
    'first_name' => 'First Name',
    'last_name' => 'Last Name',
    'address' => 'Address',
    'dba_text' => 'When you purchase the service from our website, your credit card bill will show the description as',

//Order Failed contents start here 
'payment_unsuccessful' => 'Payment Unsuccessful',
    'payment_error' => 'Oops! Something Went Wrong',
    'payment_failure_message' => 'We were unable to process your payment at this time. Don\'t worry — this can happen for a variety of reasons.',
    'what_you_can_do' => 'Here’s What You Can Do:',
    'check_payment_details' => 'Check Your Payment Details',
    'contact_bank' => 'Contact Your Bank or Card Provider',
    'try_different_payment' => 'Try a Different Payment Method',
    'need_assistance' => 'Need Assistance?',
    'reach_out' => 'If the issue persists, please don’t hesitate to reach out to us at',
    'we_are_here' => 'We’re here to help!',

//Order Success Contents start here 
'order_successful' => 'Order Successful',
    'invoice_number' => 'Invoice No:',
    'thank_you_order' => 'Thank You for Your Order!',
    'order_confirmation' => 'We’re thrilled to confirm that your order has been placed successfully with invoice number',
    'team_contact' => 'Our team will get in touch with you to kickstart our process.',
    'need_assistance' => 'Need Assistance?',
    'reach_out_for_help' => 'If you have any questions or need further details, feel free to reach out to us at',
    'no_orders_found' => 'You have no order yet!! Please order some products',
    'order_lists' => 'Order Lists',
    'order_no' => 'Order No.',
    'total_amount' => 'Total Amount',
    'status' => 'Status',
    'action' => 'Action',
    'order_information' => 'ORDER INFORMATION',
    'order_number' => 'Order Number',
    'order_date' => 'Order Date',
    'order_status' => 'Order Status',
    'payment_method' => 'Payment Method',
    'payment_status' => 'Payment Status',
    'my_orders' => 'My Orders',
    'view_details' => 'View Details',
 //comment page 
 'reply' => 'Reply',
    'cancel' => 'Cancel',


     //validation messages
     'name_required' => 'Please enter your name',
     'password_required' => 'Please enter a password',
     'password_min' => 'Your password must be at least 5 characters long',
     'password_confirmation_required' => 'Please provide a password',
     'password_confirmation_min' => 'Your password must be at least 5 characters long',
     'password_confirmation_equal' => 'Please enter the same password as above',
     'email_required' => 'Please enter a valid email address',
     'name_required' => 'Please enter your name',
     'phone_required' => 'Please enter your phone number',
     'phone_min' => 'Your number must be at least 10 digit',
     'address_required' => 'Please enter your address',
     'email_required' => 'Please enter a valid email address',
     'post_code_required' => 'Please enter your post code',
     'city_required' => 'Please enter your city',
     'state_required' => 'Please enter your state',
     'country_required' => 'Please select your country',
     'message_required' => 'Please enter your message here',
     'subject_required' => 'Please mention your subject of concern',

    'order_detail' => 'Order Details',
];
